name: Create DUBBED Package
description: Creates a DUBBED Zarf package for the requested path

inputs:
  username:
    description: Registry1 user
    required: true
  password:
    description: Registry1 PW
    required: true
  working-dir:
    description: Zarf package path
    required: true

outputs:
  latest-package-version:
    description: The latest DUBBD package version
    value: ${{ steps.latest-package-version.outputs.latest-package-version }}

runs:
  using: composite
  steps:
    - name: Login to Registry1
      uses: docker/login-action@v2
      with:
        registry: registry1.dso.mil
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        
    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.27.1

    - name: Create DUBBD
      shell: bash
      run: zarf package create --confirm
      working-directory: ${{ inputs.working-dir }}
