apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bigbang-aws-install
  region: us-west-2
  version: "1.23"

# May want to look at this for testing https://eksctl.io/usage/eks-private-cluster/
# privateCluster:
#   enabled: true

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: v1.5.2-eksbuild.1
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 2
    volumeSize: 150
    ssh:
      allow: true