package:
  create: 
    max_package_size: "1000000000"
    set:
      bigbang_version: "1.55.0"
      terraform_version: "1.4.2"
      terraform_provider_aws_version: 4.59.0
  deploy:
    set:
      domain: tom.bigbang.dev
      public_key_file: tom.bigbang.dev.key
      public_cert_file: tom.bigbang.dev.cert
