package:
  create: 
    max_package_size: "1000000000"
    set:
      bigbang_version: "1.55.0"
  deploy:
    set:
      domain: tom.bigbang.dev
      public_key_file: tom.bigbang.dev.key
      public_cert_file: tom.bigbang.dev.cert
