name: EKS Cluster Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  eksctl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install eksctl
        run: |
          sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin
          eksctl version

      - name: Create EKS cluster
        run: |
          eksctl create cluster \
          -f config.yaml
        working-directory: .github/workflows/eks
        # eventually have zarf deploy --set cluster_name=${GITHUB_SHA:0:7} \
      - name: Show Cluster
        run: |
          kubectl get nodes

      - name: Teardown EKS cluster
        # if: github.event_name == 'workflow_dispatch'
        run: echo "Cleaning up EKS cluster"
        finally: |
          eksctl delete cluster \
          -f config.yaml --disable-nodegroup-eviction --wait
        working-directory: .github/workflows/eks

