
name: DUBBD AWS

on:
  pull_request:
    branches:
      - main

jobs:
  eksctl:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.26.2
          download-init-package: true

      - name: Login to Registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          
      - name: Get short SHA
        Id: get-short-sha
        Run: |
          id=$(echo ${{github.sha}} | cut -c 1-7)
          echo "short_sha=${id}" >> $GITHUB_OUTPUT

#     - name: Set eks_cluster_name
#       id: get_cluster_name
#       env:
#         #EKS_CLUSTER_NAME: big-bang-${GITHUB_SHA:0:7}
#         SHA: ${{ github.sha }}
#       run: |
#         echo "eks_cluster_name=big-bang-${SHA:0:7}" >> $GITHUB_OUTPUT
#         #EKS_CLUSTER_NAME: big-bang-${{ github.sha }}
#         echo "$eks_cluster_name"
#         echo "$GITHUB_CONTEXT"


      - name: Package EKSCTL 
        run: zarf package create --confirm
        working-directory: .github/workflows/eks

      - name: Create EKS cluster and Zarf Init
        run: |
          echo big-bang-${{ steps.get-short-sha.outputs.id}}
          zarf package deploy zarf-package-distro-eks-multi.tar.zst --confirm --set cluster_name=big-bang-${{ steps.get-short-sha.outputs.id}}
        working-directory: .github/workflows/eks #just holds the zarf-config
        id: create-cluster
         
      - name: Create KMS Key to be replaced by UDS IaC module later
        working-directory: .github/workflows/kms
        id: create-kms
        run: |
          terraform init
          terraform apply -auto-approve --var kms_key_alias=${{ steps.get-short-sha.outputs.id}}

      - name: get KMS key
        working-directory: .github/workflows/kms
        id: get
        run: echo "kms_key_arn=$(terraform output -raw kms_key_arn)" >> $GITHUB_OUTPUT

      - name: Show Cluster
        run: |
          kubectl get nodes

      - name: Zarf init
        run: |
          zarf init -a amd64 --components=git-server --confirm

      - name: Create DUBBD-AWS
        run: zarf package create --confirm
        working-directory: aws
        timeout-minutes: 60


      - name: Deploy DUBBD-AWS
        run: |
          echo big-bang-${{ steps.get-short-sha.outputs.id}}
          zarf package deploy zarf-package-*.tar.zst --confirm --set loki_force_destroy=true --set loki_kms_key_arn=${{ steps.get.outputs.kms_key_arn }} --set name=big-bang-${{ steps.get-short-sha.outputs.id}}

        working-directory: aws
        timeout-minutes: 60

      - name: Remove DUBBD-AWS
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: aws
        timeout-minutes: 60

      - name: Teardown EKS cluster
        if: always()
        # can't do a zarf package remove since there's no kubernetes cluster.
        run: |
          ./eksctl delete cluster -f config.yaml --disable-nodegroup-eviction --wait
        working-directory: .github/workflows/eks


      - name: Remove KMS Key to be replaced by UDS IaC module later
        if: always()
        working-directory: .github/workflows/kms
        run: 
        # eventually have zarf deploy   \
          terraform destroy -auto-approve

