name: EKS Cluster Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  eksctl:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.25.0
    
      - name: Package EKSCTL 
        run: zarf package create --confirm
        working-directory: .github/workflows/eks

      - name: Create EKS cluster
        run: zarf package deploy --confirm --set cluster_name=${GITHUB_SHA:0:7}
        working-directory: .github/workflows/eks
        # eventually have zarf deploy   \
      - name: Show Cluster
        run: |
          kubectl get nodes

      - name: Teardown EKS cluster
        if: always()
        # can't do a zarf package remove since there's no kubernetes cluster.
        run: |
          ./eksctl delete cluster -f config.yaml --disable-nodegroup-eviction --wait
        working-directory: .github/workflows/eks

