name: Publish Dubbd


# Will remove before merge and make it only tags
on:
  push:
    branches:
      - auto-publish-tag
      - main

jobs:
  tag-new-version:
    # permissions: write-all
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.result.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest # use configs in release-please-config.json
          release-type: simple
      - id: result
          # run: echo "release_created=${{ steps.tag.outputs.release_created }}" >> "$GITHUB_OUTPUT" 
        run: echo "${{ toJSON(job) }}

  publish-dubbd:
    needs: tag-new-version
    uses: ./.github/workflows/publish_package.yaml
    with:
      release_created: ${{ needs.tag-new-version.outputs.release_created }}
      working_dir: defense-unicorns-distro
      package_name: zarf-package-big-bang-amd64
    secrets: inherit

  publish-dubbd-aws:
    needs: tag-new-version
    uses: ./.github/workflows/publish_package.yaml
    with:
      release_created: ${{ needs.tag-new-version.outputs.release_created }}
      working_dir: aws
      package_name: zarf-package
    secrets: inherit

  publish-dubbd-k3d:
    needs: tag-new-version
    uses: ./.github/workflows/publish_package.yaml
    with:
      release_created: ${{ needs.tag-new-version.outputs.release_created }}
      working_dir: aws
      package_name: zarf-package
    secrets: inherit